### PR TITLE
Remove token api

### PR DESCRIPTION
**Pull request by craigds**
Token API is unused and no longer works.

API tokens can be created via the website UI.

### CODE REVIEW

**Comment by rcoup** [comment]
IIUC Token API works apart from the one method that uses password auth?

**Comment by craigds** [comment]
huh. True. so we only need to remove the token creation endpoint and the console script to call it.

Though I do wonder if there's much _point_ in the rest of it...

**Comment by craigds** [comment]
ah, true. So we only need to remove the token creation endpoint and the console script to call it.

Though I do wonder if there's much _point_ in the rest of it.

**Comment by craigds** [comment]
> Is the API the only way to create referer/expiry-limited tokens?

Yes, looks like it. However, as mentioned above, token creation doesn't work at all any more. So to do that you'd have to create a token via the website, then modify it via the API to have an expiry/referer

**Pull request merged**
