### PR TITLE
Drop python 2 support

### LINKED ISSUE #34: Drop python 2 support
Supporting python 2 these days is unnecessary and is just holding back better code style.

Let's drop everything below ~3.6?

### PR DESCRIPTION
**Pull request by craigds**
Drops support for python 2. Fixes #34 

This should probably go in the next minor release, i.e 0.5, rather than a 0.4.x.

We were possibly supporting 3.3 before as well, this drops that. The minimum supported python is now 3.4.

I'd like to drop 3.4 too, but some distros still use it, so maybe in a few months.

### CODE REVIEW

**Comment by rcoup** [comment]
> This should probably go in the next minor release, i.e 0.4, rather than a 0.3.x.

👍

**Comment by rcoup** [comment]
Can you review the 2to3 casting of iterators to `list`/`dict`?

**Comment by craigds** [comment]
Just realised the released version is already 0.4.1, so this would go into 0.5.0

**Comment by craigds** [comment]
I can repro the test failures _only_ if I run them in a `-alpine` or `-slim` container (the tests use `-alpine`)

if I run them in a `python:3.4` container they work fine. It also seems to work sometimes if I don't clear the pytest cache, but I'm not entirely sure about it.

**Comment by craigds** [comment]
okay. firstly, this isn't a new issue, but since I added python 3.4/3.5 tests in buildkite, it's happening here.

The error is that the request produced by the test doesn't have a content-type header for the CSV file in the multipart upload.

I suspect that's because the `-slim` and `-alpine` variants don't have `file` installed, and so can't guess the mimetype of the file.
```
$ docker run -it --rm -v $(pwd):/app -w /app python:3.4 file --mime-type text.csv
text.csv: inode/x-empty


$ docker run -it --rm -v $(pwd):/app -w /app python:3.4-slim file --mime-type text.csv
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"file\": executable file not found in $PATH": unknown.
```

Maybe the `mimetypes` python module also uses `file` under the hood? It has similar behaviour:


```
$ docker run -it --rm -v $(pwd):/app -w /app python:3.4 python -c 'import mimetypes ; print(mimetypes.guess_type("file:///app/text.csv"))'
('text/csv', None)


$ docker run -it --rm -v $(pwd):/app -w /app python:3.4-slim python -c 'import mimetypes ; print(mimetypes.guess_type("file:///app/text.csv"))'
(None, None)
```

I'll make the test agnostic to this, because it doesn't really matter.

**Pull request merged**
